global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'whale-alert-bot'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 10s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
